service: testService

frameworkVersion: '3'

plugins:
  - ./../index.js

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    lambdaInsights: true
    architecture: x86_64

custom:
  lambdaInsights: 
    lambdaInsightsVersion: 35 #specify the Layer Version